apiVersion: v1
kind: Namespace
metadata:
  labels:
    k8s-addon: namespaces.honestbee.io
  name: "frontend"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    k8s-addon: namespaces.honestbee.io
  namespace: "frontend"
  name: "frontend-manager"
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources:
  - pods/portforward
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    k8s-addon: namespaces.honestbee.io
  namespace: "frontend"
  name: "frontend-manager"
roleRef:
  apiGroup: ""
  kind: Role
  name: "frontend-manager"
subjects:
- kind: Group
  name: honestbee:frontend-staging
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    k8s-addon: namespaces.honestbee.io
  name: "backend"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    k8s-addon: namespaces.honestbee.io
  namespace: "backend"
  name: "backend-manager"
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources:
  - pods/portforward
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    k8s-addon: namespaces.honestbee.io
  namespace: "backend"
  name: "backend-manager"
roleRef:
  apiGroup: ""
  kind: Role
  name: "backend-manager"
subjects:
- kind: Group
  name: honestbee:backend-staging
  apiGroup: rbac.authorization.k8s.io
